version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    networks:
      - zynx-network
    depends_on:
      - frontend

  # Frontend Vite/React service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - zynx-network
    command: npm run dev -- --host 0.0.0.0

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - zynx-network
    profiles:
      - production

networks:
  zynx-network:
    driver: bridge

volumes:
  logs: