// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuvaefwnolpdwtwpuzrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dmFlZndub2xwZHd0d3B1enJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODAyNDMsImV4cCI6MjA2NTc1NjI0M30.c7oK7R9DQr_fVfZHHd8NII4_3mLTD1HC-fpsmt4Ucd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});